---
container_name: "ActionsRunner"
ubuntu_version: "22.04"
container_memory: "2GB"

runner_user: "runner"
runner_password: "ChangeMe123!"

ssh_key_path: "/root/.ssh/id_rsa.pub"

github_pat: "github_pat_11EXAMPLE_TOKEN_HERE"
github_repo_url: "https://github.com/yourusername/yourrepo"
github_runner_name: "LXD-Runner"

ansible_repo_url: "https://github.com/tekore/Ansible.git"
ansible_repo_playbook: "playbooks/configure.yml"

debug_mode: false