---
- name: Create "{{ username }}" user with specified groups
  ansible.builtin.user:
    name: "{{ username }}"
    groups: adm,sudo,lxd,admin
    shell: /bin/bash
    create_home: yes

- name: Create sudoers file for "{{ username }}"
  ansible.builtin.copy:
    content: |
      # User rules for {{ username }}
      {{ username }} ALL=(ALL) NOPASSWD:ALL
    dest: "/etc/sudoers.d/91-{{ username }}"
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'

- name: Create the needed directories
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Add SSH public key to authorized_keys
  ansible.builtin.copy:
    content: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMAJedM/efW2BJhIsEOhoD350rqWXUoocusEiXCEiYKd
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'

- name: Delete ubuntu user and home directory
  ansible.builtin.user:
    name: ubuntu
    state: absent
    remove: yes
  ignore_errors: yes