---
- name: Create "{{ username }}" user with specified groups
  ansible.builtin.user:
    name: "{{ username }}"
    groups: adm,sudo,lxd
    shell: /bin/bash
    create_home: yes

- name: Create sudoers file for "{{ username }}"
  ansible.builtin.copy:
    content: |
      # User rules for {{ username }}
      {{ username }} ALL=(ALL) NOPASSWD:ALL
    dest: "/etc/sudoers.d/91-{{ username }}"
    mode: '0440'
    owner: root
    group: root
    validate: 'visudo -cf %s'

- name: Add SSH public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"

#- name: Delete ubuntu user and home directory
#  ansible.builtin.user:
#    name: ubuntu
#    state: absent
#    remove: yes
#  ignore_errors: yes